# Generated by Django 4.2.5 on 2023-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualizace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('screen', models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='vizualizace_folder/')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
