# Generated by Django 4.2.5 on 2023-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizualizace',
            name='screen',
            field=models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='website/static/vizualizace_folder/'),
        ),
    ]
