# Generated by Django 4.2.5 on 2023-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_vizualizace_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizualizace',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
