# Generated by Django 4.2.5 on 2023-09-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_vizualizace_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('screen', models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='website/static/vizualizace_folder/')),
                ('text', models.TextField(default='NA')),
                ('type', models.CharField(blank=True, choices=[('PR', 'Projekt'), ('Viz', 'Vizualizace')], max_length=10, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vizualizace',
        ),
    ]
