# Generated by Django 4.2.5 on 2023-09-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project_delete_vizualizace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(default='photo_folder/None/no-img.jpg', upload_to='website/static/photo_folder/')),
                ('rodinny_dum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
