# Generated by Django 4.2.5 on 2023-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slide',
            field=models.BooleanField(default=False),
        ),
    ]
