# Generated by Django 4.2.5 on 2023-09-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
