# Generated by Django 4.2.5 on 2023-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('RD', 'Rodinne domy'), ('INTER', 'Interiery'), ('JINE', 'Jine')], max_length=10, null=True),
        ),
    ]
