# Generated by Django 4.2.5 on 2023-09-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slide',
        ),
    ]
