# Generated by Django 4.2.5 on 2023-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_project_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='website/static/photo/None/no-img.jpg', upload_to='website/static/photo/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screen',
            field=models.ImageField(default='website/static/screen_folder/None/no-img.jpg', upload_to='website/static/screen/'),
        ),
        migrations.AlterField(
            model_name='project_photo',
            name='photo',
            field=models.ImageField(default='website/static/photo_folder/None/no-img.jpg', upload_to='website/static/photo_folder/'),
        ),
    ]
