# Generated by Django 4.2.5 on 2023-09-27 07:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contact_photo_alter_project_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(default='NA'),
        ),
    ]
