# Generated by Django 4.2.5 on 2023-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='photo/None/no-img.jpg', upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screen',
            field=models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='screen/'),
        ),
        migrations.AlterField(
            model_name='project_photo',
            name='photo',
            field=models.ImageField(default='photo_folder/None/no-img.jpg', upload_to='photo_folder/'),
        ),
    ]
